//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanLinhKienMayTinh.Areas.Admin.Models.Entites
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        public int maPhieuNhap { get; set; }
        public Nullable<int> maLinhKien { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<double> donGia { get; set; }
        public Nullable<double> tongTien { get; set; }
        public Nullable<System.DateTime> ngayThang { get; set; }
    
        public virtual LinhKien LinhKien { get; set; }
    }
}
